## Base image
FROM ubuntu:14.10
MAINTAINER Matt and Berno  bernokl@gmail.com

# Install
RUN apt-get update
RUN apt-get -y install python-software-properties
RUN apt-get -y install software-properties-common
RUN apt-get -y install wget
RUN apt-get -y install salt-minion


